import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const command = (text) => execSync(`agent-browser --session powder ${text}`, { encoding: 'utf8' }).trim();
const evaluate = (source) => JSON.parse(command(`eval -b ${Buffer.from(source, 'utf8').toString('base64')}`));
const assert = (condition, text) => { if (!condition) throw new Error(text); results.push(text); };
const results = [];
command('set viewport 375 812');
evaluate('window.__POWDER__.ui.callbacks.onHome()');
const homeBounds = JSON.parse(evaluate('JSON.stringify([...document.querySelectorAll("[data-menu] button")].filter(b=>b.offsetWidth).map(b=>({label:b.ariaLabel,x:b.getBoundingClientRect().x,right:b.getBoundingClientRect().right,bottom:b.getBoundingClientRect().bottom})))'));
assert(homeBounds.every(b => b.x >= 0 && b.right <= 375 && b.bottom <= 812), '375px 首页按钮均在屏幕内');
command('click "[data-action=start]"');
evaluate('window.__POWDER__.game.state.entities = []; null');
const bounds = JSON.parse(evaluate('JSON.stringify([...document.querySelectorAll("[data-touch]")].map(b=>({name:b.dataset.touch,x:b.getBoundingClientRect().x+b.offsetWidth/2,y:b.getBoundingClientRect().y+b.offsetHeight/2,visible:b.offsetWidth>0})))'));
assert(bounds.every(b => b.visible && b.x >= 0 && b.x <= 375 && b.y <= 812), '窄屏显示所有可用触屏按钮');
const right = bounds.find(b => b.name === 'right');
command(`mouse move ${Math.round(right.x)} ${Math.round(right.y)}`);
command('mouse down');
evaluate('new Promise(resolve=>setTimeout(()=>resolve(null),250))');
assert(evaluate('window.__POWDER__.game.state.x') > 1.2, '按住屏幕方向按钮可以持续滑行');
command('mouse up');
assert(evaluate('window.__POWDER__.getInput().steer') === 0, '松开屏幕按钮立即释放转向输入');
const jump = bounds.find(b => b.name === 'jump');
command(`mouse move ${Math.round(jump.x)} ${Math.round(jump.y)}`);
command('mouse down');
evaluate('new Promise(resolve=>setTimeout(()=>resolve(null),80))');
assert(evaluate('window.__POWDER__.game.state.y') > 0.1, '真实指针按下跳跃可以起跳');
command('mouse up');
evaluate('new Promise(resolve=>setTimeout(()=>resolve(null),1100))');
assert(evaluate('window.__POWDER__.game.state.grounded') === true, '触屏跳跃松手后正常落地');
command('click "[data-action=roll-mode]"');
command(`mouse move ${Math.round(right.x)} ${Math.round(right.y)}`);
command('mouse down');
assert(evaluate('window.__POWDER__.getInput().roll') === 1 && evaluate('window.__POWDER__.getInput().steer') === 0, '翻滚模式把方向触控切换为右翻且不同时横移');
command('mouse up');
assert(evaluate('window.__POWDER__.getInput().roll') === 0, '松开翻滚按钮不会残留旋转输入');
command('screenshot artifacts/mobile-gameplay-final.png');
command('press p');
command('click "[data-paused] [data-action=settings]"');
const settings = JSON.parse(evaluate('JSON.stringify((()=>{const r=document.querySelector("[data-settings]").getBoundingClientRect();return {top:r.top,bottom:r.bottom,right:r.right,left:r.left}})())'));
assert(settings.top >= 0 && settings.bottom <= 812 && settings.left >= 0 && settings.right <= 375, '手机设置面板完整可见');
command('screenshot artifacts/mobile-settings-final.png');
command('press Escape');
writeFileSync('artifacts/mobile-smoke.json', JSON.stringify({ passed: results.length, results }, null, 2), 'utf8');
console.log(JSON.stringify({ passed: results.length, results }, null, 2));
